name: flutainer
description: A Flutter app to manage Docker containers via Portainer API
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
#  flutter_secure_storage: ^9.2.4
  secure_store: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
